// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2MIX4hhWlN9D_9U8_xPBX7LGCSspmdv4',
    appId: '1:1075306527680:web:c7c0ca16cd6ca4707ba625',
    messagingSenderId: '1075306527680',
    projectId: 'ecommerceapp-c7832',
    authDomain: 'ecommerceapp-c7832.firebaseapp.com',
    storageBucket: 'ecommerceapp-c7832.firebasestorage.app',
    measurementId: 'G-WKH0YV4EFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUtKoK6LeKkXiIB8D13OfhHEIfDrbENI',
    appId: '1:1075306527680:android:17642310e14233417ba625',
    messagingSenderId: '1075306527680',
    projectId: 'ecommerceapp-c7832',
    storageBucket: 'ecommerceapp-c7832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf7FMV47d-vTj-VTLH9TFRbJDKmpa3vH0',
    appId: '1:1075306527680:ios:079b1637f55c292f7ba625',
    messagingSenderId: '1075306527680',
    projectId: 'ecommerceapp-c7832',
    storageBucket: 'ecommerceapp-c7832.firebasestorage.app',
    androidClientId: '1075306527680-c93gja81642o28dbat8k58pk9g6tepes.apps.googleusercontent.com',
    iosClientId: '1075306527680-25oh3rhuf3bqqiugaa8muro16v64agl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
